-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReportApi.Object.CompanyReport exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ReportApi.InputObject
import ReportApi.Interface
import ReportApi.Object
import ReportApi.Scalar
import ReportApi.ScalarCodecs
import ReportApi.Union


{-| -}
reportId : SelectionSet ReportApi.ScalarCodecs.Id ReportApi.Object.CompanyReport
reportId =
    Object.selectionForField "ScalarCodecs.Id" "reportId" [] (ReportApi.ScalarCodecs.codecs |> ReportApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
companyName : SelectionSet (Maybe String) ReportApi.Object.CompanyReport
companyName =
    Object.selectionForField "(Maybe String)" "companyName" [] (Decode.string |> Decode.nullable)


{-| -}
companyBalance : SelectionSet (Maybe Float) ReportApi.Object.CompanyReport
companyBalance =
    Object.selectionForField "(Maybe Float)" "companyBalance" [] (Decode.float |> Decode.nullable)
