-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReportApi.Object exposing (..)


type CompanyReport
    = CompanyReport
