-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReportApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import ReportApi.Scalar exposing (defaultCodecs)


type alias Id =
    ReportApi.Scalar.Id


codecs : ReportApi.Scalar.Codecs Id
codecs =
    ReportApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
